# Generated by Django 6.0.3 on 2026-04-04 08:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hw_match_score', models.FloatField(default=0.0)),
                ('ai_content_score', models.FloatField(default=0.0)),
                ('hw_verdict', models.CharField(choices=[('matched', 'Matched'), ('uncertain', 'Uncertain'), ('mismatch', 'Mismatch')], default='uncertain', max_length=20)),
                ('ai_verdict', models.CharField(choices=[('human', 'Human Written'), ('mixed', 'Mixed Content'), ('ai_generated', 'AI Generated')], default='human', max_length=20)),
                ('extracted_text', models.TextField(blank=True)),
                ('analysed_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='assignments.submission')),
            ],
        ),
    ]
