# Generated by Django 6.0.3 on 2026-04-07 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='image',
            field=models.FileField(upload_to='submissions/'),
        ),
    ]
